import { type ReactReduxContextValue } from 'react-redux';
export declare const store: import("@reduxjs/toolkit").EnhancedStore<{
    router: import("redux-first-history").RouterState;
    main: import("./main/@types").State;
    config: import("./config/@types").State;
    volume: import("./volume/@types").State;
    effects: import("./effects/common/@types").State;
    audioEffects: import("./effects/audio/audio/@types").State;
    audioBgEffects: import("./effects/audio/audioBg/@types").State;
    sideShadowEffect: import("./effects/side/shadow/@types").State;
    sideTextEffect: import("./effects/side/text/@types").State;
    backgroundEffects: import("./effects/background/@types").State;
    fontEffects: import("./effects/font/@types").State;
    bookmarks: import("./bookmarks/@types").State;
    achievements: import("./achievements/@types").State;
    segments: import("./segments/@types").State;
    counter: import("./counter/@types").State;
}, import("redux").UnknownAction, import("@reduxjs/toolkit").Tuple<[import("redux").StoreEnhancer<{
    dispatch: import("redux-thunk").ThunkDispatch<{
        router: import("redux-first-history").RouterState;
        main: import("./main/@types").State;
        config: import("./config/@types").State;
        volume: import("./volume/@types").State;
        effects: import("./effects/common/@types").State;
        audioEffects: import("./effects/audio/audio/@types").State;
        audioBgEffects: import("./effects/audio/audioBg/@types").State;
        sideShadowEffect: import("./effects/side/shadow/@types").State;
        sideTextEffect: import("./effects/side/text/@types").State;
        backgroundEffects: import("./effects/background/@types").State;
        fontEffects: import("./effects/font/@types").State;
        bookmarks: import("./bookmarks/@types").State;
        achievements: import("./achievements/@types").State;
        segments: import("./segments/@types").State;
        counter: import("./counter/@types").State;
    }, undefined, import("redux").UnknownAction>;
}>, import("redux").StoreEnhancer]>>;
export declare const history: import("history").History & {
    listenObject: boolean;
};
export type RootState = ReturnType<typeof store.getState>;
export type StoreContext = ReactReduxContextValue<RootState> | null;
export declare const storeContext: import("react").Context<StoreContext>;
export declare const useStore: import("react-redux").UseStore<import("redux").Store<{
    router: import("redux-first-history").RouterState;
    main: import("./main/@types").State;
    config: import("./config/@types").State;
    volume: import("./volume/@types").State;
    effects: import("./effects/common/@types").State;
    audioEffects: import("./effects/audio/audio/@types").State;
    audioBgEffects: import("./effects/audio/audioBg/@types").State;
    sideShadowEffect: import("./effects/side/shadow/@types").State;
    sideTextEffect: import("./effects/side/text/@types").State;
    backgroundEffects: import("./effects/background/@types").State;
    fontEffects: import("./effects/font/@types").State;
    bookmarks: import("./bookmarks/@types").State;
    achievements: import("./achievements/@types").State;
    segments: import("./segments/@types").State;
    counter: import("./counter/@types").State;
}, import("redux").UnknownAction, unknown>>;
export declare const useDispatch: import("react-redux").UseDispatch<import("redux").Dispatch<import("redux").UnknownAction>>;
export declare const useSelector: import("react-redux").UseSelector<unknown>;
